[project]
name = "whisper-local"
version = "0.1.0"
description = "A template repo for using OpenAI whisper"
requires-python = ">=3.10"
dependencies = [
    "aiofiles",
    "dotenv",
    "ffmpeg-python",
    "mcp",                # <-- Added MCP here
    "openai",
    "pydub"
]

[project.scripts]
whisper-local = "whisper_local.main:main"

[dependency-groups]
dev = [
    "mypy",
    "pre-commit",
    "pytest",
    "ruff"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

packages = ["src/whisper_local"]